config/routes.rb
Rails.application.routes.draw do

  get "messages/staff_message" => 'messages#staff_message', as: "staff_message"
  get "messages/all_student_message" => 'messages#all_student_message', as: "all_student_message"

  get "students/update_student_list" => 'students#update_student_list', as: "update_student_list"
  get "students/update_student_list_class" => 'students#update_student_list_class', as: "update_student_list_class"
  resources :students do
    collection { post :import }
  end  

  resources :staffs
  
  get "messages/update_contact_list" => 'messages#update_contact_list', as: "update_contact_list"
  get "messages/update_contact_list_class" => 'messages#update_contact_list_class', as: "update_contact_list_class"
  get "messages/update_staf_list" => 'messages#update_staff_list', as: "update_staff_list"
  get "messages/show_all_student_contact_list" => 'messages#show_all_student_contact_list', as: "show_all_student_contact_list"

  resources :messages

  resources :organizations

  get 'admin/index'

  devise_for :users
  get 'home/index'

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new",:via => [:get], :as => :login
  end
  

  root to: 'home#index'
  

end

app/models/message.rb
class Message < ActiveRecord::Base
		belongs_to :orgaization, :class_name => 'orgaization', :foreign_key => 'organization_id'
end

app/controllers/messages_controller.rb
# encoding: utf-8
class MessagesController < ApplicationController
  
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "user_layout"
  def staff_message
    @organization = Organization.where(user_id: current_user.id).first
    @message = Message.new
  end

  def all_student_message
    @organization = Organization.where(user_id: current_user.id).first
    @message = Message.new
  end

  # GET /messages
  # GET /messages.json
  def index
    @org_msg_limit = Organization.where(user_id: current_user.id)
    @messages = Message.where(organization_id: session[:current_organization_id])
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @organization = Organization.where(user_id: current_user.id).first
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  def update_staff_list
        @staff_members = Staff.where(staff_type: params[:s_type], organization_id: session[:current_organization_id])
        respond_to do |format|
          format.js
        end
  end

  def update_contact_list
    @contact = Student.where(class_name: params[:c_name], section: params[:s_name], organization_id: session[:current_organization_id])
    #print @contact.map(&:parents_contact_no)
    respond_to do |format|
      format.js 
    end
  end

  def update_contact_list_class
    @contact = Student.where(class_name: params[:c_name], organization_id: session[:current_organization_id])
    respond_to do |format|
      format.js 
    end
  end

  def show_all_student_contact_list
    section_name = params[:s_name]
    class_name = params[:c_name]
    if class_name == "None"  
      @contact = Student.where(organization_id: session[:current_organization_id])
    else
      if section_name == "None"
        @contact = Student.where(class_name: class_name, organization_id: session[:current_organization_id])
      else
         @contact = Student.where(class_name: class_name, section: section_name, organization_id: session[:current_organization_id])
      end   
    end 
    respond_to do |format|
      format.js 
    end
  end


  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    numbers = @message.sent_to.try(:split,",")
    @message.no_of_message = numbers.try(:count)
    if message_params[:sendto]=""
      @message.sendto = params[:sendto]
    end
    @message.sent_to = @message.sent_to
    org =Organization.find(session[:current_organization_id])
    respond_to do |format|
      if @message.save
        if message_params[:sms_type] == "TRANS"
          org.trans_limit = org.trans_limit.to_i - @message.no_of_message.to_i
          encoded_url = URI.encode("http://sms.hspsms.com/sendSMS?username=nitesh.mishra143@gmail.com&message="+@message.message_text+"&sendername=EXCEED&smstype="+@message.sms_type+"&numbers="+numbers.join(',')+"&apikey=eaf93dbe-bf68-43c7-8e47-c7a38bae0371")
          uri = URI.parse(encoded_url)
          Net::HTTP.get(uri)
        elsif message_params[:sms_type] == "PROMO"
          #same thing for other business logic
          org.promo_limit = org.promo_limit.to_i - @message.no_of_message.to_i
          encoded_url = URI.encode("http://sms.hspsms.com/sendSMS?username=nitesh.mishra143@gmail.com&message="+@message.message_text+"&sendername=EXCEED&smstype="+@message.sms_type+"&numbers="+numbers.join(',')+"&apikey=eaf93dbe-bf68-43c7-8e47-c7a38bae0371")
          uri = URI.parse(encoded_url)
          Net::HTTP.get(uri) 
          # puts(org.promo_limit)
        end
        org.save!
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
      end
    end

  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:message_text, :sent_to, :no_of_message, :organization_id, :sms_type, :staff_type, :sendto, :transliterateTextarea)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/edit.html.erb
<br/>

	<div class="col-md-1"></div>

	<div class="well panel-primary col-md-6">
	  	<div class="panel-heading"><center><h5>Edit Messages</h5></center></div>
	  	<div class="panel-body"><br/>

			<%= render 'form' %>

			<%= link_to 'Show', @message %> |
			<%= link_to 'Back', messages_path %>
		</div>
	</div>

	<div class="col-md-1"></div>

    <div class="well col-md-3 panel-primary">
     <div class="panel-heading"><center><h5>Quick links</h5></center></div>
      <div class="panel-body">
        <ul><br/>
          <li>
            <%= link_to 'Home', controller: "home", action: "index" %>
          </li><br/>
          <li>
            <%= link_to "Message Details", controller: "messages", action: "index" %>
            </li> <br/>
            <li>
            <%= link_to "Staff Message", controller: "messages", action: "staff_message" %>
            </li> <br/>
          <li>
            <%= link_to "Add Student", controller: "students", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Students", controller: "students", action: "index" %>
            </li> <br/>
            <li>
            <%= link_to "Add Staff", controller: "staffs", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Staffs", controller: "staffs", action: "index" %>
            </li> <br/>
        </ul>
      </div>
    </div>  		

app/views/messages/index.html.erb
<% @org_msg_limit.each do |limit| %>
  <table class="table table-striped table-hover">
    <tr><th>Remaining Promotional Messages :</th><td><%= limit.promo_limit %></td><th>Remaining Transactional Messages :</th><td><%= limit.trans_limit %></td></tr>
  </table>
<% end %>
<center><h3>Listing of Messages</h3></center>
<%= link_to 'New Message', new_message_path %>  
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th style="width: 40%;">Message text</th>
      <th style="width: 15%;" class="text-center">Sent to</th>
      <th style="width: 15%;" class="text-center">SMS Type</th>
      <th style="width: 15%;" class="text-center">No. of message</th>
      <th style="width: 15%" class="text-center"> Date </th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td style="width: 40%;"><%= message.message_text %></td>
        <td style="width: 15%;" class="text-center"><%= message.sendto %></td>
        <td style="width: 15%;" class="text-center"><%= message.sms_type %></td>
        <td style="width: 15%;" class="text-center"><%= message.no_of_message %></td>
        <td style="width: 15%;" class="text-center"><%= message.created_at.to_date %></td>
        <!-- <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
    

<br/>
<style type="text/css">
  div.tooltip-inner {
    max-width: 350px;
}

</style>
<div class="container">

  <div class="row">
    <div class="well panel-primary col-md-7">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h5>Parents Message</h5>
          </div>
          <div class="col-md-6 padding8 text-right fs16">
            <%= link_to 'Back', home_index_path, :class => "link-color mrt5" %>
          </div>
        </div>
      </div>
      <div class="panel-body"><br/>

        <%= form_for(@message) do |f| %>
          <% if @message.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

              <ul>
              <% @message.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <% unless @organization.present? %>
            <div class="danger-panel text-center"> Please <%= link_to "add organization" , new_organization_path, :class => "link-color" %> and contacts first, than you can send messages.<br></div>
          <% else %>

            <!-- Dropdown to select class and section to send messages -->
            <div class="field">
              <label>Message Text *
                (<input type="radio" name="language_type" value="English" checked /> English
                <input type="radio" name="language_type" value="Hindi" /> Hindi)
              </label>
              
              <%= f.text_area :message_text, :class => 'form-control message_text', :onkeyup => "textCounter(this,'counter',160);" %>
              <textarea id="transliterateTextarea" class="form-control transliterateTextarea" onkeyup = "textCounter(this,'counter',160);"></textarea>
              <input disabled  maxlength="3" size="3" value="160" id="counter">
            </div>
              <div class="field">
                <%= f.label :sms_type %>
                  <% if @organization.present? %>
                    <% if (@organization.promo_limit.to_i == 0) && (@organization.trans_limit.to_i >0) %>
                       <%= f.radio_button :sms_type, "TRANS", :checked=>true%>Transactional
                       <sup>
                        <a href="#" rel="tooltip" title="
                        Instructions : 
                        1. Transactional sms can be send to DND activated number.  
                        2. Transactional sms can be send at any time. "
                        <b>?</b></a>
                      </sup>
                    <% end %>
                    <% if (@organization.trans_limit.to_i == 0) && (@organization.promo_limit.to_i > 0) %>   
                      <%= f.radio_button :sms_type, "PROMO", :checked=>true %>Promotional 
                      <sup>
                        <a href="#" rel="tooltip" title="
                        Instructions :
                        1. Promotional sms can't be send to DND activated number.  
                        2. Promotional sms can be send only between 9.00AM to 9.00 PM. ">
                        <b>?</b></a>
                      </sup>
                    <% end %>
                    <% if (@organization.promo_limit.to_i > 0) && (@organization.trans_limit.to_i > 0) %>
                      <%= f.radio_button :sms_type, "TRANS", :checked=>true %>Transactional
                      <sup>
                        <a href="#" rel="tooltip" title="Instructions : 
                        1. Transactional sms can be send to DND activated number.  
                        2. Transactional sms can be send at any time.">
                        <b>?</b></a>
                      </sup>
                      <%= f.radio_button :sms_type, "PROMO" %>Promotional 
                      <sup>
                        <a href="#" rel="tooltip" title="
                        Instruction :
                        1. Promotional sms can't be sent to DND activated number.  
                        2. Promotional sms cen be send only between 9.00AM to 9.00 PM">
                        <b>?</b></a>
                      </sup>
                    <% end %>
                  <% end %>
              </div>
            <div class="field">
              <label>Class *</label>
              <%= select_tag "sendto", options_for_select(Student::CLASS_LIST, {:id=>"sendto" }), :class=> "form-control" %> <br/>
            </div>
            <div class="field">
              <label>Section * (Select None if their is no section)</label> 
              <%= select_tag "section", options_for_select(Student::SECTION_LIST, {:id=>"section"}), :class => 'form-control' %>
            </div>
            <div class="field">
              <label>Sent To *</label>
              <div class="result_div">
                <%= f.text_area :sent_to , :class => 'form-control', readonly: true %>
              </div>
            </div>
            <%= f.hidden_field :organization_id, :value => session[:current_organization_id] %>

            <div class="msg_btn ">
                <% unless @organization.present? %>
                    <div class="danger-panel text-center"> Please <%= link_to "add organization" , new_organization_path, :class => "link-color" %> and contacts first, than you can send messages.<br></div>
                <% else %>
                  <% if (@organization.promo_limit.to_i == 0) && (@organization.trans_limit.to_i == 0) %>
                    <div class="danger-panel"> Please Renew your pack to avail the facility</div> 
                  <% else %>
                      <button id="send-btn" class="btn btn-primary btn-block">Send</button>
                  <% end %>
                <% end %>
                            
            </div>
          <% end %> <!-- End of if organization not present -->
          <!-- <div class="actions">
            <%= f.submit %>
          </div> -->

        <% end %>
      </div>
    </div>  
    <div class="col-md-1"></div>

    <div class="well col-md-4 panel-primary">
       <div class="panel-heading"><center><h5>Quick links</h5></center></div>
        <div class="panel-body">
          <ul><br/>
            <li>
              <%= link_to 'Home', controller: "home", action: "index" %>
            </li><br/>
            <li>
              <%= link_to "Message Details", controller: "messages", action: "index" %>
              </li> <br/>
              <li>
              <%= link_to "Staff Message", controller: "messages", action: "staff_message" %>
              </li> <br/>
            <li>
              <%= link_to "Add Student", controller: "students", action: "new" %>
              </li> <br/>
              <li>
              <%= link_to "List of Students", controller: "students", action: "index" %>
              </li> <br/>
              <li>
              <%= link_to "Add Staff", controller: "staffs", action: "new" %>
              </li> <br/>
              <li>
              <%= link_to "List of Staffs", controller: "staffs", action: "index" %>
              </li> <br/>
          </ul>
        </div>
    </div>  
  </div>
  <div class="row">
    <div id="result_div">        
    </div>
  </div>  
<!-- script to populate list of contacts on the basis of class -->
<script>
  $(document).ready(function() {
    $('#sendto').change(function() {
        $.ajax({
           url: "<%= update_contact_list_class_path %>",
           data: {
               c_name: $("#sendto option:selected").text()
           },
           dataType: "script"
        });
    });
  });

  $(window).load(function() {

        $.ajax({
           url: "<%= update_contact_list_class_path %>",
           data: {
               c_name: $("#sendto option:selected").text()
           },
           dataType: "script"
        });

  });
</script>    

<!-- Script for Google Transliteration API. -->

<script type="text/javascript" src="https://www.google.com/jsapi"> </script>
    <script type="text/javascript">
 
        // Load the Google Transliterate API
        google.load("elements", "1", {
            packages: "transliteration"
        });
 
        function onLoad() {
            var options = {
                sourceLanguage:
                google.elements.transliteration.LanguageCode.ENGLISH,
                destinationLanguage:
                [google.elements.transliteration.LanguageCode.HINDI],
                transliterationEnabled: true
            };
 
            // Create an instance on TransliterationControl with the required
            // options.
            var control =
            new google.elements.transliteration.TransliterationControl(options);
 
            // Enable transliteration in the textbox with id
            // 'transliterateTextarea'.
            control.makeTransliteratable(['transliterateTextarea']);
        }
        google.setOnLoadCallback(onLoad);
    </script>


<!-- Script to display textarea according to language type -->

<script>
  $(function () {
    $('.message_text').show();
    $('.transliterateTextarea').hide();

    $("input[name=language_type]:radio").click(function () {

        if ($('input[name=language_type]:checked').val() == "English") {
            $('.message_text').show();

            $('.transliterateTextarea').hide();
            $('.transliterateTextarea').val(" ");

        } else if ($('input[name=language_type]:checked').val() == "Hindi") {
            $('.message_text').hide();
            $('.transliterateTextarea').show();
            $('.message_text').val(" ");
        }
    });

    $("#send-btn").click(function () {   
       msg = $('.transliterateTextarea').val();
       if (msg){
        $('.message_text').val($('.transliterateTextarea').val());
       } 
    }); 

});
</script>

<!-- script to populate list of contacts on the basis of class and section -->
<script>
  $(document).ready(function() {
    $('#section').change(function() {
        $.ajax({
           url: "<%= update_contact_list_path %>",
           data: {
               c_name: $("#sendto option:selected").text(),
               s_name: $("#section option:selected").text()
           },
           dataType: "script"
        });
    });
  });
</script>

<!-- Below function is used to validate the length of the message. -->

<script>
function textCounter(field,field2,maxlimit)
{
 var countfield = document.getElementById(field2);
 if ( field.value.length > maxlimit ) {
  field.value = field.value.substring( 0, maxlimit );
  return false;
 } else {
  countfield.value = maxlimit - field.value.length;
 }
}
</script>

<!-- Script to check the contact no selected should not exceed limit -->
<script type="text/javascript">
var $message_sent_to = $("#message_sent_to");
$message_sent_to.data("value", $message_sent_to.val());

setInterval(function() {
    var data = $message_sent_to.data("value"),
        val = $message_sent_to.val();

    if (data !== val) {
        $message_sent_to.data("value", val);
        var trans_radio = document.getElementById("message_sms_type_trans");
        var promo_radio = document.getElementById("message_sms_type_promo");
        //splitting and counting contacts on the basis of comma
        var contacts_count = $('#message_sent_to').val().split(",").length;
        var promo_msg_limit = "<%= @organization.promo_limit %>";
        var trans_msg_limit = "<%= @organization.trans_limit %>";
        //alert(promo_msg_limit);
        //alert(trans_msg_limit);
        //alert(contacts_count);
        if (trans_radio.checked){
            //alert("radio1 selected");
            if (contacts_count>trans_msg_limit) {
              alert("You have "+trans_msg_limit+" transactional sms left, can not select more than "+trans_msg_limit+" contacts");
              $('#message_sent_to').val("");
            };
        }else if (promo_radio.checked) {
            //alert("radio2 selected");
            if (contacts_count>promo_msg_limit) {
              alert("You have "+promo_msg_limit+" promotional sms left, can not select more than "+promo_msg_limit+" contacts");
              $('#message_sent_to').val("");
            };
        }
        
    }
}, 100);
</script>

<script>
$(document).ready(function () {
  $("a").tooltip({
    'selector': '',
    'placement': 'top',
    'container':'body'
  });
});


</script>

app/views/messages/staff_message.html.erb
<br/>
<div class="container">
  <div class="well panel-primary col-md-7 ">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h5>Send Message to Staff Members</h5>
          </div>
          <div class="col-md-6 padding8 text-right fs16">
            <%= link_to 'Back', home_index_path, class: "link-color mrt5" %>
          </div>
        </div>
      </div>
      <div class="panel-body"><br/>

      <%= form_for(@message) do |f| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

            <ul>
            <% @message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <% unless @organization.present? %>
          <div class="danger-panel text-center"> Please <%= link_to "add organization" , new_organization_path, :class => "link-color" %> and add contacts first, than you can send messages.<br></div>
        <% else %>
          <!-- Dropdown to select class and section to send messages -->
          <div class="field">
            <label>Message Text *
                (<input type="radio" name="language_type" value="English" checked /> English
                <input type="radio" name="language_type" value="Hindi" /> Hindi)
              </label>
              
              <%= f.text_area :message_text, :class => 'form-control message_text', :onkeyup => "textCounter(this,'counter',160);" %>
              <textarea id="transliterateTextarea" class="form-control transliterateTextarea" onkeyup = "textCounter(this,'counter',160);"></textarea>
              <input disabled  maxlength="3" size="3" value="160" id="counter">
          </div>
          
          <div class="field">
            <label>Staff Type *</label><br>
            <%= select_tag "sendto", options_for_select(Staff::STAFF_TYPE, {:id=>"sendto"}), :class => 'form-control' %>
            
          </div>
          <div class="field">
            <label>SMS Type *</label>
            <% if (@organization.promo_limit.to_i == 0) && (@organization.trans_limit.to_i > 0) %>
               <%= f.radio_button :sms_type, "TRANS", :checked=>true%>Transactional
            <% end %>
            <% if (@organization.trans_limit.to_i == 0) && (@organization.promo_limit.to_i == 0) %>   
              <%= f.radio_button :sms_type, "PROMO", :checked=>true %>Promotional 
            <% end %>
            <% if (@organization.promo_limit.to_i > 0) && (@organization.trans_limit.to_i > 0) %>
              <%= f.radio_button :sms_type, "TRANS", :checked=>true%>Transactional
              <%= f.radio_button :sms_type, "PROMO" %>Promotional 
            <% end %>

          </div>
          <div class="field">
            <label>Sent To *</label><br>
            <div class="result_div">
              <%= f.text_area :sent_to, :class => 'form-control', :required=> true, :readonly => true %>
            </div>
          </div>
          <%= f.hidden_field :organization_id, :value => session[:current_organization_id] %>
          

          <div class="msg_btn">
         	 	<% if (@organization.promo_limit.to_i == 0) && (@organization.trans_limit.to_i == 0) %>
         	 		<div class="danger-panel text-center">Please Renew your pack to avail the facility</div> 
         	 	<% else %>
            		<button id="send-btn" class="btn btn-primary btn-block">Send</button>
            <% end %>
          </div>
        <% end %>
        <!-- <div class="actions">
          <%= f.submit %>
        </div> -->
      <% end %>
    </div>
  </div>    

  <div class="col-md-1"></div>

  <div class="well col-md-4 panel-primary">
     <div class="panel-heading"><center><h5>Quick links</h5></center></div>
      <div class="panel-body">
        <ul><br/>
          <li>
            <%= link_to 'Home', controller: "home", action: "index" %>
          </li><br/>
          <li>
            <%= link_to "Message Details", controller: "messages", action: "index" %>
            </li> <br/>
            
            <li>
            <%= link_to "Student Message", controller: "messages", action: "new" %>
            </li> <br/>
          <li>
            <%= link_to "Add Student", controller: "students", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Students", controller: "students", action: "index" %>
            </li> <br/>
            <li>
            <%= link_to "Add Staff", controller: "staffs", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Staffs", controller: "staffs", action: "index" %>
            </li> <br/>
        </ul>
      </div>
  </div>
</div>
<div id="result">
          
</div>


<!-- Script for Google Transliteration API. -->

<script type="text/javascript" src="https://www.google.com/jsapi"> </script>
    <script type="text/javascript">
 
        // Load the Google Transliterate API
        google.load("elements", "1", {
            packages: "transliteration"
        });
 
        function onLoad() {
            var options = {
                sourceLanguage:
                google.elements.transliteration.LanguageCode.ENGLISH,
                destinationLanguage:
                [google.elements.transliteration.LanguageCode.HINDI],
                transliterationEnabled: true
            };
 
            // Create an instance on TransliterationControl with the required
            // options.
            var control =
            new google.elements.transliteration.TransliterationControl(options);
 
            // Enable transliteration in the textbox with id
            // 'transliterateTextarea'.
            control.makeTransliteratable(['transliterateTextarea']);
        }
        google.setOnLoadCallback(onLoad);
    </script>

<!-- Script to display textarea according to language type -->

<script>
  $(function () {
    $('.message_text').show();
    $('.transliterateTextarea').hide();

    $("input[name=language_type]:radio").click(function () {

        if ($('input[name=language_type]:checked').val() == "English") {
            $('.message_text').show();

            $('.transliterateTextarea').hide();
            $('.transliterateTextarea').val(" ");

        } else if ($('input[name=language_type]:checked').val() == "Hindi") {
            $('.message_text').hide();
            $('.transliterateTextarea').show();
            $('.message_text').val(" ");
        }
    });
    $("#send-btn").click(function () {   
      msg = $('.transliterateTextarea').val();
      if (msg){
          $('.message_text').val($('.transliterateTextarea').val());
      } 
    });
});
</script>


<!-- script to populate number on the basis of class and section -->
<script>
  $(document).ready(function() {
    $('#sendto').change(function() {
    	//alert("hello");

        $.ajax({
           url: "<%= update_staff_list_path %>",
           data: {
               s_type: $("#sendto option:selected").text()
           },
           dataType: "script"
        });
    });
  });

 
</script>
<!-- Script to send sms -->
<!-- <script>
  $(document).ready(function() {
    $('button').click(function() {
      //alert($("#class_name option:selected").text());
      // alert("sending");
      var message_text = $("#message_message_text").val();
      var send_to = $("#message_sent_to").val();
      var smstype = $('input[name=sms_type]:checked').val();
      //alert(message_text);
      alert(send_to);
      //alert(smstype);
        // $.ajax({
        //    method: "POST",
        //    url: "http://sms.hspsms.com:/sendSMS?username=9039541197&message="+message_text+"&sendername=PUBLIC&smstype="+smstype+"&numbers="+send_to+"&apikey=791cd52b-a51e-45ee-810c-fe907902fe86",
        //    crossDomain: true,
        //    data: "",
        //    dataType: "json",
        //    xhrFields: {
        //       withCredentials: true
        //     }
        // });
    });
  });
</script>
 -->
<!-- Below function is used to validate the length of the message. -->

<script>
function textCounter(field,field2,maxlimit)
{
 var countfield = document.getElementById(field2);
 if ( field.value.length > maxlimit ) {
  field.value = field.value.substring( 0, maxlimit );
  return false;
 } else {
  countfield.value = maxlimit - field.value.length;
 }
}
</script>

<!-- Script to check the contact no selected should not exceed limit -->
<script type="text/javascript">
var $message_sent_to = $("#message_sent_to");
$message_sent_to.data("value", $message_sent_to.val());

setInterval(function() {
    var data = $message_sent_to.data("value"),
        val = $message_sent_to.val();

    if (data !== val) {
        $message_sent_to.data("value", val);
        var trans_radio = document.getElementById("message_sms_type_trans");
        var promo_radio = document.getElementById("message_sms_type_promo");
        //splitting and counting contacts on the basis of comma
        var contacts_count = $('#message_sent_to').val().split(",").length;
        var promo_msg_limit = "<%= @organization.promo_limit %>";
        var trans_msg_limit = "<%= @organization.trans_limit %>";d
        alert(promo_msg_limit);
        alert(trans_msg_limit);
        //alert(contacts_count);
        if (trans_radio.checked){
            //alert("radio1 selected");
            if (contacts_count>trans_msg_limit) {
            	alert("You have "+trans_msg_limit+" transactional sms left, can not select more than "+trans_msg_limit+" contacts");
            	$('#message_sent_to').val("");
            };
        }else if (promo_radio.checked) {
            //alert("radio2 selected");
            if (contacts_count>promo_msg_limit) {
            	alert("You have "+promo_msg_limit+" promotional sms left, can not select more than "+promo_msg_limit+" contacts");
            	$('#message_sent_to').val("");
            };
        }
        
    }
}, 100);
</script>