config/routes.rb
Rails.application.routes.draw do

  get "messages/staff_message" => 'messages#staff_message', as: "staff_message"
  get "messages/all_student_message" => 'messages#all_student_message', as: "all_student_message"

  get "students/update_student_list" => 'students#update_student_list', as: "update_student_list"
  get "students/update_student_list_class" => 'students#update_student_list_class', as: "update_student_list_class"
  resources :students do
    collection { post :import }
  end  

  resources :staffs
  
  get "messages/update_contact_list" => 'messages#update_contact_list', as: "update_contact_list"
  get "messages/update_contact_list_class" => 'messages#update_contact_list_class', as: "update_contact_list_class"
  get "messages/update_staf_list" => 'messages#update_staff_list', as: "update_staff_list"
  get "messages/show_all_student_contact_list" => 'messages#show_all_student_contact_list', as: "show_all_student_contact_list"

  resources :messages

  resources :organizations

  get 'admin/index'

  devise_for :users
  get 'home/index'

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new",:via => [:get], :as => :login
  end
  

  root to: 'home#index'
  

end

app/models/student.rb
class Student < ActiveRecord::Base
	
	require 'roo'

	belongs_to :orgaization, :class_name => 'User', :foreign_key => 'user_id'
	
	CLASS_LIST = ["None", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
	SECTION_LIST = ["None", "A", "B", "C", "D", "E", "PCM", "PCB", "COM+MATHS", "COM-A", "COM-B", "COM-M"]
	GENDER_LIST = ["Male", "Female", "Others"]
	
	
=begin
def self.import(file, current_organization_id)
		
		CSV.foreach(file.path, headers: true) do |row|	
	      record = Student.find_by(:organization_id => current_organization_id,:enrollment_no => row["enrollment_no"]) || new
	      record.organization_id= current_organization_id
	      record.attributes = row.to_hash.slice(*row.to_hash.keys)
		  record.save!
	    end
	end	=end
=end


def self.import(file, current_organization_id)
  spreadsheet = open_spreadsheet(file)
  header = spreadsheet.row(1)
	# raise spreadsheet.to_yaml
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
		# raise record.to_yaml
    data = Student.where(:organization_id => current_organization_id,:enrollment_no => row["enrollment_no"].to_i)
		unless data.present?
			record = Student.new
			record.organization_id= current_organization_id
			if row["enrollment_no"].present?
				record.enrollment_no = row["enrollment_no"].to_i
			end
			if row["roll_no"].present?
				record.roll_no = row["roll_no"].to_i
			end
			if row["student_contact_no"].present?
				student_contact_no = row["student_contact_no"].to_i.to_s
				if (student_contact_no.length == 10) && (student_contact_no[0] == "7" || student_contact_no[0] == "8" || student_contact_no[0] == "9")
					record.student_contact_no = row["student_contact_no"].to_i
				end	
			end	
			if row["parents_contact_no"].present?
				parents_contact_no = row["parents_contact_no"].to_i.to_s
				if (parents_contact_no.length == 10) && (parents_contact_no[0] == "7" || parents_contact_no[0] == "8" || parents_contact_no[0] == "9")
					record.parents_contact_no = row["parents_contact_no"].to_i
				end
			end
			if row["address"].present?
				record.address = row["address"]
			end
			if row["father_name"].present?
				record.father_name = row["father_name"]
			end
			if row["mother_name"].present?
				record.mother_name = row["mother_name"]
			end
			if row["name"].present?
				record.name = row["name"]
			end
			if row["class_name"].present?
				record.class_name = row["class_name"]
			end
			if row["section"].present?
				record.section = row["section"]
			end
			if row["gender"].present?
				record.gender = row["gender"]
			end
			if row["date_of_birth"].present?
				record.date_of_birth = row["date_of_birth"]
			end
			record.save!	
		end
  end
end


def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path)
  when ".xls" then Roo::Excel.new(file.path)
  when ".xlsx" then Roo::Excelx.new(file.path)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  layout "user_layout"
  # GET /students
  # GET /students.json
  def index
    @students = Student.where(organization_id: session[:current_organization_id])
  end

  # GET /students/1
  # GET /students/1.json
  def show
    
    @student= Student.find(params[:id])

  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  def update_student_list
    
    @student_with_class = Student.where(class_name: params[:c_name], section: params[:s_name], organization_id: session[:current_organization_id])
    respond_to do |format|
      format.js 
      format.html
    end  
  end

  def update_student_list_class
    
    @student_with_class = Student.where(class_name: params[:c_name], organization_id: session[:current_organization_id])
    respond_to do |format|
      format.js 
      format.html
    end  
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    @student= Student.find(params[:id])
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student= Student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def import
    
    Student.import(params[:file], session[:current_organization_id])
    #puts @session[:current_organization_id].inspect
    redirect_to students_path, notice: "Record imported Successfully."
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.where(organization_id: session[:current_organization_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:enrollment_no, :roll_no, :address, :father_name, :mother_name, :parents_contact_no, :additional_contact_no, :parents_email, :student_contact_no, :alumni, :organization_id, :class_name, :section, :name, :gender, :date_of_birth)
    end

  
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
  <%= form_for(@student) do |f| %>
    <% if @student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <label>Name *</label><br>
      <%= f.text_field :name, :class => 'form-control', :required=> true %>
    </div>
    <div class="field">
      <label>Enrollment No. *</label><br>
      <%= f.text_field :enrollment_no, :class => 'form-control', :required=> true %>
    </div>
    <div class="field">
      <label>Roll No. *</label><br>
      <%= f.text_field :roll_no , :class => 'form-control', :required=> true%>
    </div>
    <div class="field">
      <label>Date of Birth </label><br>
      <%= f.text_field :date_of_birth , :class => 'form-control', :placeholder => 'DD/MM/YYYY' %>
    </div>
    <div class="field">
      <label>Gender </label>
      <%= f.select(:gender, Student::GENDER_LIST) %>
      &nbsp; | &nbsp;
      <label>Class Name </label>
      <%= f.select(:class_name, ["None", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]) %>
      &nbsp; | &nbsp;
      <label>Section </label>
      <%= f.select(:section, ["None", "A", "B", "C", "D", "E"]) %>
    </div>

    <div class="field">
      <label>Address </label><br>
      <%= f.text_area :address , :class => 'form-control'%>
    </div>
    <div class="field">
      <label>Father's Name </label><br>
      <%= f.text_field :father_name , :class => 'form-control'%>
    </div>
    <div class="field">
      <label>Mother's Name </label><br>
      <%= f.text_field :mother_name, :class => 'form-control' %>
    </div>
    <div class="field">
      <label>Parent's Contact No. *</label><br>
      <div class="input-group">
        <div class="input-group-addon">+91</div>
        <%= f.text_field :parents_contact_no , :class => 'form-control', :required=> true%>
      </div> <!-- End of input group -->
    </div>
    <div class="field">
      <label>Additional Contact No.</label><br>
      <div class="input-group">
        <div class="input-group-addon">+91</div>
        <%= f.text_field :additional_contact_no, :class => 'form-control' %> 
      </div> <!-- End of input-group -->
    </div>
    <div class="field">
      <label>Parent's Email</label><br>
      <%= f.text_field :parents_email, :class => 'form-control' %>
    </div>
    <div class="field">
      <label>Student's Contact No.</label><br>
      <div class="input-group">
        <div class="input-group-addon">+91</div>
        <%= f.text_field :student_contact_no, :class => 'form-control' %>
      </div> <!-- End of input group -->
    </div>
    <div class="field">
      <%= f.label :alumni %>
      <%= f.check_box :alumni %>
    </div>
    <%= f.hidden_field :organization_id, :value => session[:current_organization_id] %>

    <div class="actions">
      <%= f.submit  :class => 'btn btn-primary btn-block form-control'%>
    </div>
  <% end %>

app/views/students/_show_students.html.erb
<style type="text/css">

</style>

<% if @student_with_class.empty? %>
	<div class="window-center text-center well">
		<h4>No records to display</h4>
	</div>
<% else %>
	<div class="horizontal_scroll vertical_scroll">
	<table class="table table-striped table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Enrollment No.</th>
	      <th>Roll No.</th>
	      <th>Date of Birth</th>
	      <th>Gender</th>
	      <th>Class</th>
	      <th>Section</th>
	      <th>Address</th>
	      <th>Parent's Contact No.</th>
	      <th>Additional Contact No:</th>
	      <th>Parent's Email</th>
	      <th>Student's Contact No.</th>
	      <th>Alumni</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @student_with_class.each do |student| %>
	      <tr>
	        <td><%= student.name %></td>
	        <td><%= student.enrollment_no %></td>
	        <td><%= student.roll_no %></td>
	        <td><%= student.date_of_birth %></td>
	        <td><%= student.gender %></td>
	        <td><%= student.class_name %></td>
	        <td><%= student.section %></td>
	        <td><%= student.address %></td>
	        <td><%= student.parents_contact_no %></td>
	        <td><%= student.additional_contact_no %></td>
	        <td><%= student.parents_email %></td>
	        <td><%= student.student_contact_no %></td>
	        <td><%= student.alumni %></td>
	        <td><%= link_to 'Show', student %></td>
	        <td><%= link_to 'Edit', edit_student_path(student) %></td>
	        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	</div>
<% end %>

app/views/students/edit.html.erb
<br/>

<div class="col-md-3"></div>

<div class="well panel-primary col-md-6">
  	<div class="panel-heading"><center><h5>Edit Student Details</h5></center></div>
  	<div class="panel-body"><br/>

		<%= render 'form' %>

		<%= link_to 'Show', @student , :class => 'link_color'%> |
		<%= link_to 'Back', students_path, :class => 'link_color' %>

	</div>
</div>	

app/views/students/index.html.erb
<div class="container">
  <div class="panel-primary">
    <div class="panel-heading">
      <div class="row">
        <div class="col-md-3 fs16 padding8">
          <%= link_to "Back", home_index_path, class: "link-color" %>
          |
          <%= link_to 'Add New Student', new_student_path, class: "link-color" %>
        </div>
        <div class="col-md-4 text-center">
          <h5>List of Students</h5>
        </div>
        <div class="col-md-5">
          <div class="row pdt7">
            <div class="col-md-6">
              <label>Class :</label>
              <%= select_tag "class_name", options_for_select(Student::CLASS_LIST), {:class=>"select-box"} %>
            </div>
            <div class="col-md-6">
              <label>Section :</label>
              <%= select_tag "section", options_for_select(Student::SECTION_LIST), {:class=>'select-box'} %>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>

  <div id="result_div">
    <div class="window-center text-center well">
      <h4>Select class and section to see the record</h4>
    </div>
  </div>
</div>  

<script>
  $(document).ready(function() {
    $('#section').change(function() {
        $.ajax({
           url: "<%= update_student_list_path %>",
           data: {
               c_name: $("#class_name option:selected").text(),
               s_name: $("#section option:selected").text()
           },
           dataType: "script"
        });
    });
  });

  $(window).load(function() {
        $.ajax({
           url: "<%= update_student_list_path %>",
           data: {
               c_name: $("#class_name option:selected").text(),
               s_name: $("#section option:selected").text()
           },
           dataType: "script"
        });
  });
</script>
<script>
  $(document).ready(function() {
    $('#class_name').change(function() {
        $.ajax({
           url: "<%= update_student_list_class_path %>",
           data: {
               c_name: $("#class_name option:selected").text()
           },
           dataType: "script"
        });
    });
  });
</script>

app/views/students/new.html.erb
<br/>

<div class="col-md-1"></div>

	<div class="well panel-primary col-md-6">
	  	<div class="panel-heading">
        <div class="row">
          <div class="col-md-6">
            <h5>Students Registration</h5>
          </div>
          <div class="col-md-6 padding8 text-right fs16">
            <%= link_to 'Back', home_index_path, class: "link-color mrt5" %>
          </div>
        </div>
      </div>
	  	<div class="panel-body"><br/>
			<%= render 'form' %>
		</div>	
	</div>
	
	<div class=" col-md-4">
		<div class="well panel-primary">
		<div class="panel-heading"><center><h5>Import Student's List</h5></center></div>
	  	<div class="panel-body"><br/>
      <p><strong>Instructions:</strong></p>
      <ul>
        <li>Follow the instruction strictly.</li>
        <li>Format supported - csv, xlsx and xls.</li>
        <li>Before importing the CSV file check the <b> <%= link_to "Sample", "/data/student.csv", class: "link-underline" %> </b> and import it accordingly.</li>
        <li>Before importing the Excel file check the <b> <%= link_to "Sample", "/data/student.xlsx", class: "link-underline" %> </b>  and import it accordingly. </li>
        <li>Don't use comma in the address.</li>
      </ul><br/>
			<%= form_tag import_students_path, multipart: true do %>
				<%= file_field_tag :file , :required=> true%> <br/>
				<%= submit_tag "Import" , :class => "btn btn-primary btn-block" %>
			<% end %>	
		</div>
		</div>
		<br/> <br/>
  <div class="well  panel-primary">
     <div class="panel-heading"><center><h5>Quick links</h5></center></div>
      <div class="panel-body">
        <ul><br/>
          <li>
            <%= link_to 'Home', controller: "home", action: "index" %>
          </li><br/>
          <li>
            <%= link_to "Message Details", controller: "messages", action: "index" %>
            </li> <br/>
            <li>
            <%= link_to "Staff Message", controller: "messages", action: "staff_message" %>
            </li> <br/>
            <li>
            <%= link_to "Student Message", controller: "messages", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Students", controller: "students", action: "index" %>
            </li> <br/>
            <li>
            <%= link_to "Add Staff", controller: "staffs", action: "new" %>
            </li> <br/>
            <li>
            <%= link_to "List of Staffs", controller: "staffs", action: "index" %>
            </li> <br/>
        </ul>
      </div>
  </div> 

</div>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<br/>
<div class="col-md-2">
</div>

<div class="col-md-7">
<p><%= link_to 'Back', new_student_path %> <span class="pull-right"><%= link_to 'Edit', edit_student_path(@student) %> </span></p>
<div class="table-responsive">
<table class="table table-hover">
<tr>
  <td><strong>Name:</strong></td>
  <td><%= @student.name %></td>
</tr>

<tr>
  <td><strong>Enrollment no:</strong></td>
  <td><%= @student.enrollment_no %></td>
</tr>

<tr>
  <td><strong>Roll no:</strong></td>
  <td><%= @student.roll_no %></td>
</tr>

<tr>
  <td><strong>Date of Birth:</strong></td>
  <td><%= @student.date_of_birth %></td>
</tr>

<tr>
  <td><strong>Gender:</strong></td>
  <td><%= @student.gender %></td>
</tr>

<tr>
  <td><strong>Class:</strong></td>
  <td><%= @student.class_name %></td>
</tr>

<tr>
  <td><strong>Section:</strong></td>
  <td><%= @student.section %></td>
</tr>

<tr>
  <td><strong>Address:</strong></td>
  <td><%= @student.address %></td>
</tr>

<tr>
  <td><strong>Father name:</strong></td>
  <td><%= @student.father_name %></td>
</tr>

<tr>
  <td><strong>Mother name:</strong></td>
  <td><%= @student.mother_name %></td>
</tr>

<tr>
  <td><strong>Parents contact no:</strong></td>
  <td><%= @student.parents_contact_no %></td>
</tr>

<tr>
  <td><strong>Additional contact no:</strong></td>
  <td><%= @student.additional_contact_no %></td>
</tr>

<tr>
  <td><strong>Parents email:</strong></td>
  <td><%= @student.parents_email %></td>
</tr>

<tr>
  <td><strong>Student contact no:</strong></td>
  <td><%= @student.student_contact_no %></td>
</tr>

<tr>
  <td><strong>Alumni:</strong></td>
  <td><%= @student.alumni %></td>
</tr>
</table>
</div>
</div>

app/views/students/update_student_list.js.erb
$('#result_div').html("<%= j (render 'show_students') %>");

app/views/students/update_student_list_class.js.erb
$('#result_div').html("<%= j (render 'show_students') %>");