config/routes.rb
Rails.application.routes.draw do

  get "messages/staff_message" => 'messages#staff_message', as: "staff_message"
  get "messages/all_student_message" => 'messages#all_student_message', as: "all_student_message"

  get "students/update_student_list" => 'students#update_student_list', as: "update_student_list"
  get "students/update_student_list_class" => 'students#update_student_list_class', as: "update_student_list_class"
  resources :students do
    collection { post :import }
  end  

  resources :staffs
  
  get "messages/update_contact_list" => 'messages#update_contact_list', as: "update_contact_list"
  get "messages/update_contact_list_class" => 'messages#update_contact_list_class', as: "update_contact_list_class"
  get "messages/update_staf_list" => 'messages#update_staff_list', as: "update_staff_list"
  get "messages/show_all_student_contact_list" => 'messages#show_all_student_contact_list', as: "show_all_student_contact_list"

  resources :messages

  resources :organizations

  get 'admin/index'

  devise_for :users
  get 'home/index'

  devise_scope :user do
    match '/sign-in' => "devise/sessions#new",:via => [:get], :as => :login
  end
  

  root to: 'home#index'
  

end

app/views/admin/index.html.erb
<style type="text/css">
	.link_color{
		color: #000000;
	}
</style>

<br>
<div class="container">
	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 bhoechie-tab-container">
			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3 bhoechie-tab-menu">
				<div class="list-group">
					<a href="#" class="list-group-item active text-center">
						<h4>Profile</h4>
					</a>
					<a href="#" class="list-group-item  text-center">
						<h4>Manage Staff</h4>
					</a>
					<a href="#" class="list-group-item text-center">
						<h4>Students</h4>
					</a>
					<a href="#" class="list-group-item text-center">
						<h4>Send Message</h4>
					</a>
					<a href="#" class="list-group-item text-center">
						<h4>Reports</h4>
					</a>
					<a href="#" class="list-group-item text-center">
						<h4>Settings</h4>
					</a>
				</div>
			</div>
			<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9 bhoechie-tab">
				<% if @allowed_user %>
					<div class="bhoechie-tab-content active fs16">
						<center><h4>Profile</h4></center>
						<hr class="hr-color" />
						<p align="center" class="fs16">Welcome <strong><%= current_user.email %></strong></p>
						<% unless @org.present? %>
							<div class="well">
 								<%= link_to "Add Organization" , new_organization_path, class: "link-underline" %>
 							</div> <!-- End of well -->
						<% else %>
							<div class="well">
								<%= link_to "Edit Organization Profile", edit_organization_path(@org), class: "link-underline"  %>
							</div>
						<% end %>
					</div>
					<div class="bhoechie-tab-content">
						<center><h4>Manage Staff</h4></center>
						<hr class="hr-color" />
						<div class="well">
						<ul class="fs16">
							<% if @org.present? %>
								<li>
									<%= link_to "Add Staff Member", new_staff_path, class: "link-underline" %>
								</li>
								<br>
								<li>
									<%= link_to "List of Staff Member", staffs_path, class: "link-underline" %>
								</li>
							<% else %>
								<li class="fs16">
									<a class="link link-underline"> Add Staff Member</a>
									<span class="red">
										(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
									</span>
								</li>
								<br>
								<li class="fs16">
									<a class="link link-underline"> List of Staff Member</a>
									<span class="red">
										(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
									</span>
								</li>
							<% end %>	
						</ul>
						</div>
					</div>
					<div class="bhoechie-tab-content">
						<center><h4>Students</h4></center>
						<hr class="hr-color" />
						<div class="well">
						<ul class="fs16">
							<% if @org.present? %>
								<li>
									<%= link_to "Add Student", new_student_path, class: "link-underline" %>
								</li>
								<br>
								<li>
									<%= link_to "List of Student", students_path, class: "link-underline" %>
								</li>
							<% else %>	
								<li class="fs16">
									<a class="link link-underline"> Add Student</a>
									<span class="red">
										(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
									</span>
								</li>
								<br>
								<li class="fs16">
									<a class="link link-underline"> List of Student</a>
									<span class="red">
										(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
									</span>
								</li>
							<% end %>
						</ul>
						</div>
					</div>
					<div class="bhoechie-tab-content">
						<center><h4>Send Message</h4></center>
						<hr class="hr-color"/>
						<div class="well">
							<ul class="fs16">
								<% if @org.present? %>
									<li>
										<%= link_to "Parents", new_message_path, class: "link-underline" %>
									</li>
									<br/>
									<li>
										<%= link_to "Students", all_student_message_path, class: "link-underline" %>
									</li>
									<br>
									<li>
										<%= link_to "Staffs", staff_message_path, class: "link-underline" %>
									</li>
								<% else %>	
									<li class="fs16">
										<a class="link link-underline"> Parents</a>
										<span class="red">
											(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
										</span>
									</li>
									<br>
									<li class="fs16">
										<a class="link link-underline"> All Students</a>
										<span class="red">
											(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
										</span>
									</li>
									<br>
									<li class="fs16">
										<a class="link link-underline">Staffs</a>
										<span class="red">
											(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
										</span>
									</li>
								<% end %>
							</ul>	
						</div> <!-- End of well -->
					</div>
					<div class="bhoechie-tab-content">
						<center><h4>Reports</h4></center>
						<hr class="hr-color" />
						<div class="well">
							<ul class="fs16">
								<p class="fs16">Check Message History and remaining messages</p>
								<% if @org.present? %>
									<li><%= link_to "Message History", messages_path, class: "link-underline" %>
								<% else %>	
									<li class="fs16">
										<a class="link link-underline">Message History</a>
										<span class="red">
											(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
										</span>
									</li>
								<% end %>
								</li>
							</ul>
						</div> <!-- End of well -->
					</div>
					<div class="bhoechie-tab-content">
						<center><h4>Settings</h4></center>
						<hr class="hr-color" />
						<div class="well">
							<ul class="fs16">
								<% if @org.present? %>
									<li><%= link_to "Change Password", messages_path, class: "link-underline" %>
								<% else %>	
									<li class="fs16">
										<a class="link link-underline">Change Password</a>
										<span class="red">
											(Please <%= link_to "add organization" , new_organization_path, :class => "link-underline red" %> first, than you can access the feature)
										</span>
									</li>
								<% end %>
								</li>
							</ul>
						</div> <!-- End of well -->
					</div>
				<% else %>
					<div class="bhoechie-tab-content active">
						<h5>Thanx for activating. Kindly contact customer suh5port for allowing to access the feature of the app.</h5>
					</div>
					<div class="bhoechie-tab-content">
						<center><h5>You don't have sufficient permission to access the account. Kindly contact our customer support.</h5></center>
					</div>
					<div class="bhoechie-tab-content">
						<center><h5>You don't have sufficient permission to access the account. Kindly contact our customer support.</h5></center>
					</div>
					<div class="bhoechie-tab-content">
						<center><h5>You don't have sufficient permission to access the account. Kindly contact our customer support.</h5></center>
					</div>
					<div class="bhoechie-tab-content">
						<center><h5>You don't have sufficient permission to access the account. Kindly contact our customer support.</h5></center>
					</div>
					<div class="bhoechie-tab-content">
						<center><h5>You don't have sufficient permission to access the account. Kindly contact our customer support.</h5></center>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>	